### ISSUE TITLE
A Tutorial on Unidimensional Unfolding: From Automatic Item Generation to Insightful Inferences

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#1003]
https://osf.io/preprints/psyarxiv/5hnkz_v1
https://osf.io/pqjhv/

**Comment by saviranadela** [comment]
emailed

**Comment by SamuelEnrique** [comment]
@saviranadela please find below:

[franco_2024_unfolding.csv](https://github.com/user-attachments/files/21455920/franco_2024_unfolding.csv)

```
*** This Do File creates tables from the A Tutorial on Unidimensional Unfolding: From Automatic Item Generation to Insightful Inferences study ***

* clear
clear

* import main dataset
import delimited "CoombsGPT.csv", clear

* drop old id
drop id

* drop unnecessary variables
drop run timestartedutc timefinishedutc minutesspent 

* renames covariates
rename sex cov_sex
rename gender cov_gender
rename age cov_age
rename scholarity cov_education

* adds new id
gen id = _n

* reorder variables
order id cov_*, first

* save cleaned dataset
save "franco_2024_unfolding.csv", replace

* creates long data from wide data
local question_cols  p_1  p_2  p_3  p_4  p_5  p_6

tempfile longdata
save `longdata', emptyok replace

foreach var of local question_cols {
    preserve
    keep id cov_* `var'
    gen item = "`var'"
    rename `var' resp
    order id item resp
    append using `longdata'
    save `longdata', replace
    restore
}

use `longdata', clear

drop p_1  p_2  p_3  p_4  p_5  p_6

drop if missing(item) | item == ""

* encode any needed variables
gen resp2 = resp
drop resp
rename resp2 resp

* reorder variables
order id item resp cov_*

* sort responses
sort item id 

* saves final dataset
export delimited using "franco_2024_unfolding.csv", replace
```

**Comment by ben-domingue** [comment]
@SamuelEnrique i have added data to upload queue so we are good there. two questions:
1. is it in the data dictionary? 
2. i am not seeing code on github so i don't think there ever was a pull request. have you made one?

**Comment by SamuelEnrique** [comment]
@saviranadela can you check again? I've pushed it again. See snippet below:

<img width="1167" height="121" alt="Image" src="https://github.com/user-attachments/assets/24a88b40-2c53-4786-8c30-b22c0a769363" />

**Comment by ben-domingue** [comment]
@SamuelEnrique i am still not seeing it in my list of pull requests. i am seeing it on *your* fork:
https://github.com/SamuelEnrique/irw/blob/main/data/franco_2024_unfolding.do
my sense is that the issue is that you need to push it to the main branch. @saviranadela does this sound right?
