### ISSUE TITLE
Feeling heard: Operationalizing a key concept for social relations

### ISSUE THREAD

**Issue by ben-domingue** [ben-domingue/irw#556]
https://dataverse.nl/dataset.xhtml?persistentId=doi:10.34894/IHNKUN

**Comment by KingArthur0205** [comment]
Working on this

**Comment by KingArthur0205** [comment]
The original datasets were super messy.
Data:
[Fh_Okcsr_Roos_2022_CSV.zip](https://github.com/user-attachments/files/17440780/Fh_Okcsr_Roos_2022_CSV.zip)

Code:
```
# Paper:
# Data: https://dataverse.nl/dataset.xhtml?persistentId=doi:10.34894/IHNKUN

library(haven)
library(dplyr)
library(tidyr)
library(openxlsx)
library(readr)
library(readxl)
library(sas7bdat)

remove_na <- function(df) {
  df <- df[!(rowSums(is.na(df[, -which(names(df) %in% c("id"))])) == (ncol(df) - 1)), ]
  return(df)
}

study1_df <- read_sav("Feeling heard - Questionnaire data Study 1.sav") 
study2_df <- read_sav("Feeling heard - Questionnaire data Study 2.sav") 
study3_df <- read_sav("Feeling heard - Questionnaire data Study 3.sav") 

study1_df[] <- lapply(study1_df, function(col) { # Remove column labels for each column
  attr(col, "label") <- NULL
  return(col)
})

exclude_rows <- c(9, 30, 32, 40, 56, 66, 72, 81, 84, 90, 101, 106, 110, 114, 131, 150, 162, 167, 170, 177, 189, 197, 203)

# Exclude the rows from study1 dataframe using slice
study1_df <- study1_df %>%
  slice(-exclude_rows)

study2_df[] <- lapply(study2_df, function(col) { # Remove column labels for each column
  attr(col, "label") <- NULL
  return(col)
})

study3_df[] <- lapply(study3_df, function(col) { # Remove column labels for each column
  attr(col, "label") <- NULL
  return(col)
})

study1_df <- study1_df %>%
  mutate(id = row_number() )

study2_df <- study2_df %>%
  mutate(id = row_number() )

study3_df <- study3_df %>%
  mutate(id = row_number() )

heard_df <- study1_df |>
  select(ends_with("11"), ends_with("12"),id, -FL_13_DO_FL_11)
heard_df <- remove_na(heard_df)
heard_df[] <- lapply(heard_df, function(x) if (is.labelled(x)) as.numeric(x) else x)
heard_df <- pivot_longer(heard_df, cols=-c(id), names_to="item", values_to="resp")

Voice_df <- study1_df |>
  select(ends_with("_1"), ends_with("_2"),ends_with("_3"),id)
Voice_df <- remove_na(Voice_df)
Voice_df[] <- lapply(Voice_df, function(x) if (is.labelled(x)) as.numeric(x) else x)
Voice_df <- pivot_longer(Voice_df, cols=-c(id), names_to="item", values_to="resp")

Attention_df <- study1_df |>
  select(ends_with("_4"), ends_with("_5"),ends_with("_6"),id)
Attention_df  <- remove_na(Attention_df )
Attention_df[] <- lapply(Attention_df, function(x) if (is.labelled(x)) as.numeric(x) else x)
Attention_df  <- pivot_longer(Attention_df, cols=-c(id), names_to="item", values_to="resp")


Empathy_df <- study1_df |>
  select(ends_with("_7"), ends_with("_8"),ends_with("_9"),id)
Empathy_df <- remove_na(Empathy_df)
Empathy_df[] <- lapply(Empathy_df, function(x) if (is.labelled(x)) as.numeric(x) else x)
Empathy_df <- pivot_longer(Empathy_df, cols=-c(id), names_to="item", values_to="resp")


Respect_df <- study1_df |>
  select(ends_with("_10"), ends_with("_11"),ends_with("_12"),id,-FL_13_DO_FL_11)
Respect_df <- remove_na(Respect_df)
Respect_df[] <- lapply(Respect_df, function(x) if (is.labelled(x)) as.numeric(x) else x)
Respect_df <- pivot_longer(Respect_df, cols=-c(id), names_to="item", values_to="resp")


Common_ground_df <- study1_df |>
  select(ends_with("_13"), ends_with("_14"),ends_with("_15"),id)
Common_ground_df <- remove_na(Common_ground_df)
Common_ground_df[] <- lapply(Common_ground_df, function(x) if (is.labelled(x)) as.numeric(x) else x)
Common_ground_df <- pivot_longer(Common_ground_df, cols=-c(id), names_to="item", values_to="resp")

Disagree_df <- study1_df |>
  select(ends_with("_16"),id)
Disagree_df <- remove_na(Disagree_df)
Disagree_df[] <- lapply(Disagree_df, function(x) if (is.labelled(x)) as.numeric(x) else x)
Disagree_df <- pivot_longer(Disagree_df, cols=-c(id), names_to="item", values_to="resp")

heard_df$group <- "feeling heard Group"
Voice_df$group <- "Voice Group"
Attention_df$group <- "Attention Group"
Empathy_df$group <- "Empathy Group"
Respect_df$group <- "Respect Group"
Common_ground_df$group <- "Common ground Group"
Disagree_df$group <- "Disagree Group"


study1_Feeling_Heard_df <- rbind(heard_df, 
                                 Voice_df,
                                 Attention_df, 
                                 Empathy_df,
                                 Respect_df,
                                 Common_ground_df,
                                 Disagree_df)

save(study1_Feeling_Heard_df, file="Fh_Okcsr_Roos_2022_study1_Feeling_Heard.Rdata")
write.csv(study1_Feeling_Heard_df, "Fh_Okcsr_Roos_2022_study1_Feeling_Heard.csv", row.names=FALSE)

Reliability_df <- study2_df |>
  select(starts_with("Q5.1"),id)
Reliability_df   <- remove_na(Reliability_df)
Reliability_df  <- pivot_longer(Reliability_df , cols=-c(id), names_to="item", values_to="resp")
                          
Convergent_Validity_conversational_intimacy_df <- study2_df |>
  select(starts_with("Q6.1"),id)
Convergent_Validity_conversational_intimacy_df  <- remove_na(Convergent_Validity_conversational_intimacy_df)
Convergent_Validity_conversational_intimacy_df <- pivot_longer(Convergent_Validity_conversational_intimacy_df , cols=-c(id), names_to="item", values_to="resp")

Convergent_Validity_conversational_dominance_df<- study2_df |>
  select(starts_with("Q75"),id)
Convergent_Validity_conversational_dominance_df  <- remove_na(Convergent_Validity_conversational_dominance_df)
Convergent_Validity_conversational_dominance_df <- pivot_longer(Convergent_Validity_conversational_dominance_df, cols=-c(id), names_to="item", values_to="resp")

Individualized_Trust_df <- study2_df |>
  select(starts_with("Q8.1"),id)
Individualized_Trust_df  <- remove_na(Individualized_Trust_df)
Individualized_Trust_df <- pivot_longer(Individualized_Trust_df , cols=-c(id), names_to="item", values_to="resp")

Affective_Attraction_df <- study2_df |>
  select(starts_with("Q9"),id)
Affective_Attraction_df  <- remove_na(Affective_Attraction_df)
Affective_Attraction_df <- pivot_longer(Affective_Attraction_df , cols=-c(id), names_to="item", values_to="resp")

Perceived_partner_responsiveness_df <- study2_df |>
  select(starts_with("Q10.1"),id)
Perceived_partner_responsiveness_df <- remove_na(Perceived_partner_responsiveness_df )
Perceived_partner_responsiveness_df  <- pivot_longer(Perceived_partner_responsiveness_df, cols=-c(id), names_to="item", values_to="resp")

Perceived_goal_accomplishment_df <- study2_df |>
  select(starts_with("Q11.1"),id)
Perceived_goal_accomplishment_df <- remove_na(Perceived_goal_accomplishment_df)
Perceived_goal_accomplishment_df  <- pivot_longer(Perceived_goal_accomplishment_df, cols=-c(id), names_to="item", values_to="resp")

Communication_Apprehension_df <- study2_df |>
  select(starts_with("Q12.1"),id)
Communication_Apprehension_df <- remove_na(Communication_Apprehension_df)
Communication_Apprehension_df <- pivot_longer(Communication_Apprehension_df, cols=-c(id), names_to="item", values_to="resp")

Reliability_df$group <- "Reliability Group"
Convergent_Validity_conversational_intimacy_df $group <- "Convergent Validity conversational intimacy Group"
Convergent_Validity_conversational_dominance_df $group <- "Convergent Validity conversational dominance Group"
Individualized_Trust_df$group <- "Individualized Trust Group"
Affective_Attraction_df$group <- "Affective Attraction Group"
Perceived_partner_responsiveness_df$group  <- "Perceived partner responsiveness Group"
Perceived_goal_accomplishment_df$group  <- "Perceived goal accomplishment Group"
Communication_Apprehension_df$group <- "Communication Apprehension Group"

convert_labelled_to_numeric <- function(df) {
  df[] <- lapply(df, function(x) {
    if (is.labelled(x)) {
      # If it's a labelled column, convert it to numeric (which removes labels)
      as.numeric(x)
    } else {
      x
    }
  })
  return(df)
}

# Apply this conversion to all data frames
Reliability_df <- convert_labelled_to_numeric(Reliability_df)
Convergent_Validity_conversational_intimacy_df <- convert_labelled_to_numeric(Convergent_Validity_conversational_intimacy_df )
Convergent_Validity_conversational_dominance_df <- convert_labelled_to_numeric(Convergent_Validity_conversational_dominance_df)
Individualized_Trust_df <- convert_labelled_to_numeric(Individualized_Trust_df)
Affective_Attraction_df <- convert_labelled_to_numeric(Affective_Attraction_df)
Perceived_partner_responsiveness_df <- convert_labelled_to_numeric(Perceived_partner_responsiveness_df)
Perceived_goal_accomplishment_df <- convert_labelled_to_numeric(Perceived_goal_accomplishment_df)
Communication_Apprehension_df <- convert_labelled_to_numeric(Communication_Apprehension_df)

study2_Feeling_Heard_df <- rbind(Reliability_df, 
                                 Convergent_Validity_conversational_intimacy_df,
                                 Convergent_Validity_conversational_dominance_df,
                                 Individualized_Trust_df, 
                                 Affective_Attraction_df,
                                 Perceived_partner_responsiveness_df,
                                 Perceived_goal_accomplishment_df,
                                 Communication_Apprehension_df)
study2_Feeling_Heard_df$resp <- ifelse(study2_Feeling_Heard_df$resp >= 10 & study2_Feeling_Heard_df$resp <= 18, study2_Feeling_Heard_df$resp - 9, study2_Feeling_Heard_df$resp)

save(study2_Feeling_Heard_df, file="Fh_Okcsr_Roos_2022_study2_Feeling_Heard.Rdata")
write.csv(study2_Feeling_Heard_df, "Fh_Okcsr_Roos_2022_study2_Feeling_Heard.csv", row.names=FALSE)

# Negative Avoidance
negative_avoidance_df <- study2_df %>%
  select(Q13.1_1, Q23.1_1, Q13.1_2, Q23.1_2,id)
negative_avoidance_df  <- remove_na(negative_avoidance_df )
negative_avoidance_df <- pivot_longer(negative_avoidance_df , cols=-c(id), names_to="item", values_to="resp")

# Positive Avoidance
positive_avoidance_df <- study2_df  %>%
  select(Q13.1_3, Q23.1_3, Q13.1_4, Q23.1_4, id)
positive_avoidance_df <- remove_na(positive_avoidance_df )
positive_avoidance_df <- pivot_longer(positive_avoidance_df, cols=-c(id), names_to="item", values_to="resp")

# Negative Approach
negative_approach_df <- study2_df  %>%
  select(Q13.1_5, Q23.1_5, Q13.1_6, Q23.1_6, id)
negative_approach_df <- remove_na(negative_approach_df)
negative_approach_df<- pivot_longer(negative_approach_df , cols=-c(id), names_to="item", values_to="resp")

# Positive Approach
positive_approach_df <- study2_df  %>%
  select(Q13.1_7, Q23.1_7, Q13.1_8, Q23.1_8, id)
positive_approach_df <- remove_na(positive_approach_df)
positive_approach_df <- pivot_longer(positive_approach_df, cols=-c(id), names_to="item", values_to="resp")

negative_avoidance_df <- convert_labelled_to_numeric(negative_avoidance_df)
positive_avoidance_df <- convert_labelled_to_numeric(positive_avoidance_df)
negative_approach_df <- convert_labelled_to_numeric(negative_approach_df)
positive_approach_df <- convert_labelled_to_numeric(positive_approach_df)

study2_not_feeling_heard_df <- rbind(negative_avoidance_df, 
                                     positive_avoidance_df,
                                     negative_approach_df, 
                                     positive_approach_df)

save(study2_not_feeling_heard_df, file="Fh_Okcsr_Roos_2022_study2_not_Feeling_Heard.Rdata")
write.csv(study2_not_feeling_heard_df, "Fh_Okcsr_Roos_2022_study2_not_Feeling_Heard.csv", row.names=FALSE)

self_express_df <- study3_df |>
  select(matches("^Q(4\\.4|6\\.4|8\\.4)_(1|2|3|4|5|6|7|8|9)$"), id)
self_express_df <- remove_na(self_express_df)
self_express_df <- pivot_longer(self_express_df, cols=-c(id), names_to="item", values_to="resp")

solidarity_df <- study3_df |>
  select(matches("^Q(4\\.2|6\\.2|8\\.2)_(1|2|3|4|5|6)$"), id)
solidarity_df <- remove_na(solidarity_df)
solidarity_df <- pivot_longer(solidarity_df, cols=-c(id), names_to="item", values_to="resp")

conversational_flow_df <- study3_df |>
  select(matches("^Q(4\\.1|6\\.1|8\\.1)_(1|2|3|4|5)$"), id)
conversational_flow_df <- remove_na(conversational_flow_df)
conversational_flow_df <- pivot_longer(conversational_flow_df, cols=-c(id), names_to="item", values_to="resp")

self_esteem_df<- study3_df |>
  select(matches("^Q(4\\.3|6\\.3|8\\.3)_(1|2|3|4|5|6)$"), id)
self_esteem_df <- remove_na(self_esteem_df)
self_esteem_df <- pivot_longer(self_esteem_df, cols=-c(id), names_to="item", values_to="resp")

other_expression_df <- study3_df |>
  select(matches("^Q(4\\.5|6\\.5|8\\.5)_(1|2|3|4|5|6)$"), id)
other_expression_df <- remove_na(other_expression_df)
other_expression_df <- pivot_longer(other_expression_df, cols=-c(id), names_to="item", values_to="resp")

self_express_df$group <- "self expression Group"
solidarity_df$group <- "solidarity Group"
conversational_flow_df$group <- "conversational flow Group"
self_esteem_df$group  <- "self esteem group"
other_expression_df$group <- "other expression Group"

self_express_df <- convert_labelled_to_numeric(self_express_df)
solidarity_df <- convert_labelled_to_numeric(solidarity_df)
conversational_flow_df <- convert_labelled_to_numeric(conversational_flow_df)
self_esteem_df <- convert_labelled_to_numeric(self_esteem_df)
other_expression_df <- convert_labelled_to_numeric(other_expression_df)

study3_Feeling_Heard_df <- rbind(self_express_df, 
                                 solidarity_df,
                                 conversational_flow_df, 
                                 self_esteem_df,
                                 other_expression_df)

save(study3_Feeling_Heard_df, file="Fh_Okcsr_Roos_2022_study3_Feeling_Heard.Rdata")
write.csv(study3_Feeling_Heard_df , "Fh_Okcsr_Roos_2022_study3_Feeling_Heard.csv", row.names=FALSE)

```

**Comment by ben-domingue** [comment]
@KingArthur0205 i'm inclined to cut this one. fewer respondents than items is (in most cases) not that worthwhile especially when the N of people is <100. 
Fh_Okcsr_Roos_2022_study3_Feeling_Heard.Rdata

**Comment by ben-domingue** [comment]
and could these be combined?

**Comment by KingArthur0205** [comment]
@ben-domingue 
1. **Removal of Study 3 Data**: Certainly! I’ve removed the Study 3 data.

2. **Merging Decisions:**
        (a) Within each study, I’ve merged the sub-scales that assess participants' feelings about having conversations with others, covering aspects such as trust, feelings, and emotions.
        (b) I’ve decided to keep the data from Study 1 and Study 2 separate because:
                (1) They measure different aspects. Study 1 specifically targets online conversations, focusing on participants' physical and emotional responses during these interactions.
                (2) Study 2 looks at conversations in a broader context, including online interactions. The intent is to apply theories about traditional conversations from Study 2 to validate conclusions drawn from Study 1.

**Comment by ben-domingue** [comment]
@KingArthur0205 i just downloaded the data and am still seeing study 3. i can just remove that one manually NBD but wanted to double check to see if anything else had changed.

**Comment by KingArthur0205** [comment]
@ben-domingue I haven't changed the data for this one as I'd like to confirm if you'd agree that "the 2 datasets in Study 2 can be merged as they measured positve/negative feelings about conversations, which share some commonalities"

**Comment by ben-domingue** [comment]
so the study 2 dataset: are they the same scales in different contexts?

**Comment by KingArthur0205** [comment]
All questions were asked in the context of how participants felt during conversations. The difference is that the negative data frame focused on negative feelings (e.g., "I’m afraid to engage in conversation"), while the positive data frame focused on positive feelings (e.g., "I feel understood").

**Comment by ben-domingue** [comment]
i think in that case i'd be inclined to merge and just include a variable for context.

**Comment by KingArthur0205** [comment]
@ben-domingue Got it. In this case, I'll include a group and have the values marked as "positive" and "negative"

**Comment by KingArthur0205** [comment]
@ben-domingue The code and data have been updated in the cell above. Let me know if you find it acceptable, and I’ll create the PR.

**Comment by ben-domingue** [comment]
ok ship PR @KingArthur0205

**Comment by KingArthur0205** [comment]
PR for this one: https://github.com/ben-domingue/irw/pull/646/files
